version: '3.8'

services:
  main:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    ports:
      - "8000:8000"

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:sql_mesh_state
    networks:
      - platform_network

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  
  trino_dwh:
    image: trinodb/trino:474
    restart: unless-stopped
    environment:
      - TRINO_ENVIRONMENT=production
    ports:
      - "8080:8080"
    networks:
      - platform_network
    volumes:
      - ../trino/config.properties:/etc/trino/config.properties
      - ../trino/platform_catalog.properties:/etc/trino/catalog/platform_catalog.properties
      - ../data/synth_customer.duckdb:/opt/duckdb/synth_customer.duckdb

networks:
  platform_network:
    driver: bridge